name: lingola_app
description: "Lingola - Dil öğrenme uygulaması."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: ^3.10.7

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.7.0
  flutter_svg: ^2.0.10+1
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  uses-material-design: true

  assets:
    - assets/app_icon.png
    - assets/splash/Layer_1.png
    - assets/splash/splash1.png
    - assets/splash/splash2.png
    - assets/splash/splash3.png
    - assets/onboard/onboard.png
    - assets/onboard/OBJECTS.png
    - assets/onboard/objects_01.png
    - assets/onboard/OBJECTS_2.png
    - assets/onboard/Frame.svg
    - assets/icons/google.svg
    - assets/icons/apple.svg
    - assets/icons/facebook.svg
    - assets/icons/legal.svg
    - assets/icons/tech.svg
    - assets/icons/medicine.svg
    - assets/icons/chart-histogram.svg
    - assets/icons/megaphone.svg
    - assets/icons/engineering.svg
    - assets/icons/education.svg
    - assets/icons/tourism.svg
    - assets/icons/sales.svg
    - assets/icons/customer-support.svg
    - assets/icons/hr.svg
    - assets/icons/entrepreneurship.svg
    - assets/icons/truck.svg
    - assets/icons/data.svg
    - assets/bayrak/flag_english.svg
    - assets/bayrak/flag_german.svg
    - assets/bayrak/flag_italian.svg
    - assets/bayrak/flag_french.svg
    - assets/bayrak/flag_japanese.svg
    - assets/bayrak/Spain.png
    - assets/bayrak/flag_russian.svg
    - assets/bayrak/flag_turkish.svg
    - assets/bayrak/flag_korean.svg
    - assets/bayrak/flag_hindi.svg
    - assets/bayrak/flag_portuguese.svg
    - assets/seviye/message-circle.svg
    - assets/seviye/ai-users.svg
    - assets/seviye/Clip path group (4).svg
    - assets/seviye/Clip path group (5).svg
    - assets/seviye/star-4 (1).svg
    - assets/seviye/award (2).svg
    - assets/seviye/rectangle_165.svg
    - assets/seviye/vector_11.svg
    - assets/seviye/time_fast.svg
    - assets/seviye/vector_12.svg
    - assets/dummy/image 2.png
    - assets/icons/Vector.svg
    - assets/icons/frame_notification.svg
    - assets/icons/bildirim2.svg
    - assets/icons/mask_group.svg
    - assets/icons/mask_group_1.svg
    - assets/icons/vector_search.svg
    - assets/icons/rectangle_141.svg
    - assets/icons/frame_terms.svg
    - assets/icons/vector_premium.svg
    - assets/icons/kupa.svg
    - assets/icons/frame_saved_words.svg
    - assets/icons/frame_dictionary.svg
    - assets/icons/icon_arrow_right.svg
    - assets/icons/icon_arrow_back_next.svg
    - assets/icons/nav_home.svg
    - assets/icons/nav_learn.svg
    - assets/icons/nav_library.svg
    - assets/icons/nav_profil.svg
    - assets/icons/icon_delete.svg
    - assets/icons/icon_frame_arrow.svg
    - assets/icons/icon_translate.svg
    - assets/icons/icon_mic.svg
    - assets/icons/icon_premium.svg
    - assets/icons/icon_share.svg
    - assets/icons/icon_faq.svg
    - assets/icons/icon_rate.svg
    - assets/icons/icon_signout.svg
    - assets/icons/icon_notifications_list.svg
    - assets/icons/icon_photo_camera.svg
    - assets/icons/icon_photo_gallery.svg
    - assets/icons/icon_save.svg
    - assets/icons/icon_filter_button.svg
    - assets/icons/icon_hint.svg
    - assets/icons/icon_heart_save.svg
    - assets/icons/icon_tutorial_hand.svg
    - assets/icons/icon_tutorial_arrow_prev.svg
    - assets/icons/icon_tutorial_arrow_next.svg
    - assets/icons/yıldız.svg
    - assets/icons/ses.svg
    - assets/icons/icon_search_library.svg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package

# App icon (Lingola Job - globe + tie)
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/app_icon.png"
  remove_alpha_ios: true
